Repository Timanchik/LB-6, pull requests merged in 2020-06, with the labels that each got.

#7 Библиотека
  PythonApplication1.sln
  PythonApplication1/PythonApplication1.py
  PythonApplication1/PythonApplication1.pyproj
  PythonApplication1/class1.py
Labels: TRPO, Visual Studio

#9 Update .travis.yml
  .travis.yml
Labels: CI, TRPO

#10 for release
  .travis.yml
Labels: CI, TRPO

#11 Release
  .travis.yml
  PythonApplication1.sln
  PythonApplication1/PythonApplication1.py
  PythonApplication1/PythonApplication1.pyproj
  PythonApplication1/class1.py
  PythonApplication1/test_auth.py
Labels: CI, TRPO

#12 Pre-release
  .travis.yml
Labels: CI, TRPO

#13 Test release
  .travis.yml
Labels: CI

#16 Pre-Release
  .travis.yml
  .travis/default.yml
  .travis/release.yml
Labels: CI, TRPO

#17 Release
  .travis.yml
  .travis/default.yml
  .travis/release.yml
Labels: CI, TRPO

#18 Pre-release
  .travis.yml
Labels: CI, TRPO

#19 Release
  .travis.yml
Labels: CI, TRPO

#20 Issue 6
  .travis.yml
  .travis/default.yml
  .travis/release.yml
Labels: CI

#23 Issue 6
  .travis.yml
  .travis/default.yml
  .travis/release.yml
Labels: CI
